refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console

  garmin:
    kind: rolling_file
    path: /var/log/requests.log
    encoder:
      pattern: "{d} - {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 30 mb
      roller:
        kind: fixed_window
        pattern: /var/log/step_{}.gz
        count: 5
        base: 1

root:
  level: debug
  appenders:
    - stdout
    - garmin

loggers:
  app::backend::db:
    level: debug

  app::garmin:
    level: debug
    appenders:
      - garmin
      - stdout
    additive: false